# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dsl2skillm/v1/command.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'dsl2skillm/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64sl2skillm/v1/command.proto\x12\rdsl2skillm.v1\"\r\n\x0bListCommand\",\n\x0cQueryCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"\x1f\n\x0fValidateCommand\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1f\n\rHealthCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\",\n\x0eResolveCommand\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"N\n\x0fRegisterCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tspec_json\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\t\"/\n\x11UnregisterCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"b\n\rInvokeCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x11\n\targs_json\x18\x02 \x01(\t\x12\x12\n\ninput_text\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x0c\n\x04\x66ile\x18\x05 \x01(\t\"?\n\x0cPatchCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x11\n\tspec_json\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\"\x8b\x04\n\x0b\x44slEnvelope\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12*\n\x04list\x18\n \x01(\x0b\x32\x1a.dsl2skillm.v1.ListCommandH\x00\x12,\n\x05query\x18\x0b \x01(\x0b\x32\x1b.dsl2skillm.v1.QueryCommandH\x00\x12\x32\n\x08validate\x18\x0c \x01(\x0b\x32\x1e.dsl2skillm.v1.ValidateCommandH\x00\x12.\n\x06health\x18\r \x01(\x0b\x32\x1c.dsl2skillm.v1.HealthCommandH\x00\x12\x30\n\x07resolve\x18\x0e \x01(\x0b\x32\x1d.dsl2skillm.v1.ResolveCommandH\x00\x12\x32\n\x08register\x18\x0f \x01(\x0b\x32\x1e.dsl2skillm.v1.RegisterCommandH\x00\x12\x36\n\nunregister\x18\x10 \x01(\x0b\x32 .dsl2skillm.v1.UnregisterCommandH\x00\x12.\n\x06invoke\x18\x11 \x01(\x0b\x32\x1c.dsl2skillm.v1.InvokeCommandH\x00\x12,\n\x05patch\x18\x12 \x01(\x0b\x32\x1b.dsl2skillm.v1.PatchCommandH\x00\x12\x14\n\x0c\x64\x65\x66\x61ult_file\x18\x14 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x15 \x01(\tB\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dsl2skillm.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTCOMMAND']._serialized_start=46
  _globals['_LISTCOMMAND']._serialized_end=59
  _globals['_QUERYCOMMAND']._serialized_start=61
  _globals['_QUERYCOMMAND']._serialized_end=105
  _globals['_VALIDATECOMMAND']._serialized_start=107
  _globals['_VALIDATECOMMAND']._serialized_end=138
  _globals['_HEALTHCOMMAND']._serialized_start=140
  _globals['_HEALTHCOMMAND']._serialized_end=171
  _globals['_RESOLVECOMMAND']._serialized_start=173
  _globals['_RESOLVECOMMAND']._serialized_end=217
  _globals['_REGISTERCOMMAND']._serialized_start=219
  _globals['_REGISTERCOMMAND']._serialized_end=297
  _globals['_UNREGISTERCOMMAND']._serialized_start=299
  _globals['_UNREGISTERCOMMAND']._serialized_end=346
  _globals['_INVOKECOMMAND']._serialized_start=348
  _globals['_INVOKECOMMAND']._serialized_end=446
  _globals['_PATCHCOMMAND']._serialized_start=448
  _globals['_PATCHCOMMAND']._serialized_end=511
  _globals['_DSLENVELOPE']._serialized_start=514
  _globals['_DSLENVELOPE']._serialized_end=1037
# @@protoc_insertion_point(module_scope)
